apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: scenario-01-cascading-failure
  namespace: monitoring
  labels:
    release: prometheus
    role: alert-rules
    scenario: "01"
spec:
  groups:
  - name: scenario_01_cascading_failure
    interval: 10s
    rules:
    - alert: CascadingUpstreamErrors
      expr: |
        rate(http_client_requests_total{
          app="api-gateway",
          status_code=~"5..",
          destination_service="checkout"
        }[2m]) > 0
      for: 20s
      labels:
        severity: critical
        scenario: cascade
        scenario_id: "01"
      annotations:
        summary: "{{ $labels.app }} seeing upstream errors to {{ $labels.destination_service }}"
        description: "api-gateway is receiving 5xx errors from checkout service. Root cause may be downstream."
        alert_namespace: "{{ $labels.namespace }}"
        alert_service: "{{ $labels.app }}"
        alert_destination: "{{ $labels.destination_service }}"
        alert_status_code: "{{ $labels.status_code }}"

